import logo_ko from "./images/footer/ktwiz_ko.svg"
import facebook from "./images/footer/facebook.png"
import instagram from "./images/footer/instagram.png"
import naver from "./images/footer/naver.png"
import youtube from "./images/footer/youtube.png"
import subBackground from "./images/common/subBackground.png"
import subBg from "./images/common/subBg.png"
import landingBackground01 from "./images/landing/landingBackground.png"
import landingBackground02 from "./images/landing/bg01.png"
import item01 from "./images/landing/bg02.png"
import item02 from "./images/landing/bg03.png"
import rightArrow from "./images/landing/rightArrow.png"
import leftArrow from "./images/landing/leftArrow.png"
import doosan from "./images/landing/doosan.png"
import ktwiz from "./images/common/newLogo.png"
import nc from "./images/landing/nc.png"
import shopItem from "./images/landing/shopItem.png"
import ktwizEnLogo from "./images/common/ktwiz.png"

export {logo_ko,facebook,instagram,naver,youtube,subBackground,subBg,landingBackground01,landingBackground02,rightArrow,leftArrow,doosan,ktwiz,nc,item01,item02,shopItem,ktwizEnLogo};